### ISSUE TITLE
other color for non-digit-buttons 

### ISSUE THREAD

**Issue by xstable** [astush1001/Calculate-Me#18]
I suggest to change the colors of non-digit buttons. This way it's more intuitive to use this calculator. 
I take this issue, if you like. 

![image](https://github.com/astush1001/Calculate-Me/assets/1778068/1bac1d51-bcb2-4667-aa71-86d083ca91d5)

**Comment by astush1001** [comment]
Yeah Go ahead But maintain the color relevant to the other buttons.
