### ISSUE TITLE
Button Click Effect

### ISSUE THREAD

**Issue by astush1001** [astush1001/Calculate-Me#2]
Add effects on clicking the buttons of the calculator.

**Comment by Soumya624** [comment]
Hi @astush1001 ,

Can you explain a bit more? What sort of effects?

Thanks!

**Comment by yashwanthvarma18** [comment]
Hello @astush1001 , I'm eager to contribute. Please assign me

**Comment by suresh8919** [comment]
Hello @astush1001  Please assign me

**Comment by Madhura-saw** [comment]
Hi @astush1001, could I be assigned to this issue?

**Comment by yashwanthvarma18** [comment]
hey @astush1001 why dont you assign me i will get the work done
