### ISSUE TITLE
Bksp button overflow on inspect element.

### ISSUE THREAD

**Issue by astush1001** [astush1001/Calculate-Me#26]
![Screenshot 2023-10-05 162819](https://github.com/astush1001/Calculate-Me/assets/146252802/0b91c8e8-2fc9-4b79-beca-13410b74f832)

**Comment by vanshajkataria** [comment]
May I work on this?

**Comment by astush1001** [comment]
I got one solution for this but you may try a different approach.

**Comment by vanshajkataria** [comment]
I will try to add an arrow at this media query or changing the font size. Which one would you like me to do?

**Comment by astush1001** [comment]
Don't change the font size..
Try the other one and I'll be adding one more issue regarding this.... see if you can do something about it too.

**Comment by vanshajkataria** [comment]
ok I will do the needful

**Comment by vanshajkataria** [comment]
I have created the PR for this issue.

**Comment by vanshajkataria** [comment]
@astush1001 this PR is not counting on my Hacktoberfest

**Comment by astush1001** [comment]
I have no idea man ..
I have already labelled it as hacktober-accepted
