### ISSUE TITLE
Clear History

### ISSUE THREAD

**Issue by astush1001** [astush1001/Calculate-Me#6]
A feature to clear previous records should be there.

**Comment by vanshajkataria** [comment]
Hey, I would like to work on this issue.
Please assign it to me.

**Comment by astush1001** [comment]
Yeah ! Go ahead please.

**Comment by vanshajkataria** [comment]
I am also working on the UI a little bit if you don't mind.

**Comment by astush1001** [comment]
Yeah no problem. Valuable changes are always welcome.

**Comment by vanshajkataria** [comment]
Ok Great!

**Comment by astush1001** [comment]
Hey @vanshajkataria Are you still working on this ?
Please add the feature to clear the previous records.

**Comment by vanshajkataria** [comment]
Yes @astush1001, I am working on it. Right now my exams are being held so I was busy. Sorry for the delay,
I will complete it by today/tomorrow.

**Comment by vanshajkataria** [comment]
I have generated the pull request
I have added a reset button to clear the existing history from local storage.
